from __future__ import annotations

from typing import Any, Iterable, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from core.ingest import IngestSummary
    from core.retriever import RetrievalResults


class LLMClient(Protocol):
    """Protocol matching openai.OpenAI's chat.completions interface."""
    chat: Any


class EmbeddingModel(Protocol):
    def get_text_embedding(self, text: str) -> list[float]: ...
    def get_query_embedding(self, query: str) -> list[float]: ...
    def get_text_embedding_batch(self, texts: list[str]) -> list[list[float]]: ...


class VectorStore(Protocol):
    def count_chunks(self) -> int: ...
    def count_documents(self) -> int: ...
    def iter_records(self) -> list[dict[str, Any]]: ...
    def upsert_chunks(self, chunks: list[Any]) -> None: ...
    def delete_by_document_id(self, document_id: str) -> int: ...
    def clear(self) -> None: ...
    def get_record(self, chunk_id: str) -> dict[str, Any] | None: ...


class DocumentManifest(Protocol):
    def list_documents(self) -> list[dict[str, Any]]: ...
    def get(self, document_id: str) -> dict[str, Any] | None: ...
    def find_by_path(self, source_path: str) -> dict[str, Any] | None: ...
    def upsert_document(self, record: dict[str, Any]) -> None: ...
    def remove_document(self, document_id: str) -> None: ...
    def update_tags(self, document_id: str, tags: list[str]) -> dict[str, Any] | None: ...
    def clear(self) -> None: ...


class Retriever(Protocol):
    def retrieve(
        self,
        query: str,
        chat_history: list[dict[str, Any]] | None = None,
        mode: str = "hybrid",
        top_k: int | None = None,
        filters: dict[str, Any] | None = None,
    ) -> RetrievalResults: ...


class Generator(Protocol):
    def stream_generate(
        self,
        query: str,
        retrieval_results: RetrievalResults,
        chat_history: list[dict[str, Any]] | None = None,
        model: str | None = None,
    ) -> Iterable[tuple[str, str]]: ...


class ChatStore(Protocol):
    current_id: str | None
    conversations: dict[str, Any]

    def create_conversation(self, title: str = "新对话", **metadata: Any) -> Any: ...
    def switch_conversation(self, conversation_id: str) -> bool: ...
    def delete_conversation(self, conversation_id: str) -> bool: ...
    def rename_conversation(self, conversation_id: str, title: str) -> bool: ...
    def list_conversations(self) -> list[dict[str, Any]]: ...
    def add_user_message(self, content: str, save: bool = True, **metadata: Any) -> Any: ...
    def add_assistant_message(self, content: str, save: bool = True, **metadata: Any) -> Any: ...


class IngestEngine(Protocol):
    def scan_files(self, root_dir: Any = None) -> list[Any]: ...
    def add_files(self, file_paths: list[Any], tags: list[str] | None = None) -> IngestSummary: ...
    def rebuild_index(self) -> IngestSummary: ...
    def force_rebuild_index(self) -> IngestSummary: ...
    def delete_file(self, document_id: str) -> dict[str, Any]: ...
    def clear_index(self) -> dict[str, Any]: ...
    def get_index_stats(self) -> dict[str, Any]: ...
    def list_documents(self) -> list[dict[str, Any]]: ...
    def update_document_tags(self, document_id: str, tags: list[str]) -> dict[str, Any] | None: ...


class ConfigProvider(Protocol):
    """Protocol for providing API keys from config sources."""
    def get_api_key(self) -> str: ...
